### ISSUE TITLE
마이페이지, 메이트 글쓰기 - 동물 정보 가져오기 함수

### ISSUE THREAD

**Issue by Gruzam0615** [PetPotal/PetPotal#159]
현재 동물 등록은 정상적으로 작동합니다.

나의 동물 리스트를 조회할 수 있는 함수가 없어서 생성이 필요합니다.

**Comment by Gruzam0615** [comment]
postman으로 작성된 backend api 리스트 참고
animals -> 반려동물 정보 검색(사용자 색인기준) 항목 참고

**Comment by doch2130** [comment]
메이트 글쓰기 - 동물정보 가져오기 추가 완료

**Comment by doch2130** [comment]
마이 페이지 - 동물정보 가져오기 추가 완료
