### ISSUE TITLE
마이페이지 - 동물 정보 수정

### ISSUE THREAD

**Issue by doch2130** [PetPotal/PetPotal#175]
1. 동물 정보 수정
-> category1, category2 정보 업데이트가 안됨

2. 동물 이미지 변경
-> 함수 성공 시 data 반환 값 이미지 주소 필요

**Comment by Gruzam0615** [comment]
category1은 동물종류(개, 고양이 등) 를 분류하는 컬럼인데 이 값도 변경이 필요한지 궁금합니다

**Comment by doch2130** [comment]
기능은 있는게 낫지 않을까 생각합니다.

**Comment by doch2130** [comment]
정상작동 확인
