### ISSUE TITLE
로그인 기능 오류 수정 요청

### ISSUE THREAD

**Issue by Gruzam0615** [PetPotal/PetPotal#70]
DB에 없는 ID로 로그인 시도할 경우
성공 및 토큰 생성 확인

develop-backend
passport-local 로그인 수정

해당 커밋 버전으로는 테스트 안해봤습니다.

**Comment by Gruzam0615** [comment]
"DB에 없는 ID로 로그인 시도할 경우
성공 및 토큰 생성 확인"

최신 커밋에서는 위의 문제점 발견되지 않았습니다.
최신 커밋을 pull 하고 재확인 부탁드립니다.

**Comment by doch2130** [comment]
최신버전으로 정상 작동 확인
최신버전으로 체크하면서 frontend 코드 변경이 필요하여 일부 수정 작업 완료

**Comment by doch2130** [comment]
정상작동 완료
