### ISSUE TITLE
회원가입 - 주소 정보 기입 변경 작업

### ISSUE THREAD

**Issue by Gruzam0615** [PetPotal/PetPotal#71]
**일단 보류**

회원가입 시
address1 - 시
address2 - 구
address3 - 시구동(로)
상세주소 저장 X
으로 설정이 되어 있지만,

address1 - 시
address2 - 구
address3 - 동(로)
address4 - 상세주소
으로 변경 필요

**Comment by doch2130** [comment]
데이터 연동 정상 확인

**Comment by doch2130** [comment]
address3 데이터 정리 필요

**Comment by doch2130** [comment]
수정 완료
