### ISSUE TITLE
회원탈퇴 기능 추가 요청

### ISSUE THREAD

**Issue by Gruzam0615** [PetPotal/PetPotal#75]
**axios
 method: delete
 url: users/withdrawal**

필요한 결과값

성공
responseCode: 200

실패
responseCode: 

회원탈퇴 성공 시 클라이언트 쿠키 삭제 필요

**Comment by doch2130** [comment]
회원탈퇴 기능 에러 발생

Users.update() 함수로 인한 에러로 판단

**Comment by Gruzam0615** [comment]
[

[230515_PetPotal_Users_sql.sql.zip](https://github.com/PetPotal/PetPotal/files/11476991/230515_PetPotal_Users_sql.sql.zip)

](url)
데이터베이스 테이블 구조 차이로 인한 문제로 보임 첨부한 sql에 내용으로 Users 테이블 업데이트 후 재확인 요청합니다.

**Comment by doch2130** [comment]
회원탈퇴 정상 확인
- 데이터 삭제가 아닌
- usersStatus 값(3) 변경 확인
- modifiedDate 값 변경 확인
