### ISSUE TITLE
마이페이지 - 회원정보 가져오기 기능 추가 요청

### ISSUE THREAD

**Issue by Gruzam0615** [PetPotal/PetPotal#77]
임시로 사용중인 코드
UsersController.test2

**axios
 method: post
 url: users/mypage/userInfoLoad**

**필요한 결과값**

**성공**
statusCode: 200
message: 'Success'
data: response

response 값 => 
Users.findOne({
  attributes: [
	'account',
	'name',
	'nickName',
	'phone',
	'email',
	'address1',
	'address2',
	'address3',
	'address4',
  ],
)

**실패**
responseCode:
message:

**Comment by doch2130** [comment]
데이터 연동 정상 확인
