### ISSUE TITLE
로그아웃 에러 발생 확인 요청

### ISSUE THREAD

**Issue by doch2130** [PetPotal/PetPotal#84]
로그인 후 로그아웃 시 에러 발생 확인

1. 케이스 1
- 로그인 후 바로 로그아웃 하는 경우
- 정상 작동

2. 케이스 2
- 로그인 후 새로고침 하는 경우
- 에러 발생
- 새로고침하는 경우 세션이 변경되서 에러가 발생하는것으로 판단됨

**Comment by Gruzam0615** [comment]
에러 확인 불가
develop-backend 최신 커밋 반영후 재확인 바람

**Comment by doch2130** [comment]
node 코드 nodemon 으로 실행 시 서버 재부팅으로 인한 현상으로 확인
이상없음
