### ISSUE TITLE
마이페이지 - 펫 이미지 등록 함수 추가 요청

### ISSUE THREAD

**Issue by doch2130** [PetPotal/PetPotal#91]
**펫 이미지 등록 함수 추가 요청**
**요청 axios**
axios {
	url: 'animals/updatePetImage',
	method: 'post',
	data: imageFile
}

**.single('animalsPhotos')**

imageFile
=> 메이트 글쓰기처럼 이미지 파일은 5개가 아닌 1개만 사용

글쓰기 등록과는 별도로 이미지 등록 함수 필요
저장 폴더 : data/animals

**임시 설정 값**
**app.js**
=> static3 임시 사용 변수 (app.js 설정 필요)
app.use('/static3', express.static(__dirname + '/data/animals'));

**기본적으로 필요한 리턴 값**
const result = `http://${req.hostname}:3010/static3/${req.file.filename}`;
res.send(result);

**Comment by Gruzam0615** [comment]
별도의 메서드가 필요한 이유가 궁금합니다.

**Comment by doch2130** [comment]
프로세스 체크 후 다시 말씀드리겠습니다.

**Comment by doch2130** [comment]
별도의 메서드는 필요하지 않을 것으로 판단되며,
펫 등록 함수에 이미지 저장하는 함수를 포함시켜서 적용시키면 될 것 같습니다.
